# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/crash_stats',
                'doc_host': 'https://aibistin.github.io',
                'git_url': 'https://github.com/aibistin/crash_stats',
                'lib_path': 'crash_stats'},
  'syms': {'crash_stats.core': {'crash_stats.core.foo': ('core.html#foo', 'crash_stats/core.py')}}}
