# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/crash_stats',
                'doc_host': 'https://aibistin.github.io',
                'git_url': 'https://github.com/aibistin/crash_stats',
                'lib_path': 'crash_stats'},
  'syms': {}}
